'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ChakavakServiceWS
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ChequeResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ChequeResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HeaderField As ChakavakServiceWS.Header
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResponseField As ChakavakServiceWS.Response
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Header() As ChakavakServiceWS.Header
            Get
                Return Me.HeaderField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HeaderField, value) <> true) Then
                    Me.HeaderField = value
                    Me.RaisePropertyChanged("Header")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Response() As ChakavakServiceWS.Response
            Get
                Return Me.ResponseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResponseField, value) <> true) Then
                    Me.ResponseField = value
                    Me.RaisePropertyChanged("Response")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Header", [Namespace]:="http://schemas.datacontract.org/2004/07/com.cbi.chakavak.chequeSchema"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Header
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private amountFieldField As String
        
        Private chequeIDFieldField As String
        
        Private depositDateFieldField As String
        
        Private settlementDateFieldField As String
        
        Private userNameFieldField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property amountField() As String
            Get
                Return Me.amountFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.amountFieldField, value) <> true) Then
                    Me.amountFieldField = value
                    Me.RaisePropertyChanged("amountField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property chequeIDField() As String
            Get
                Return Me.chequeIDFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.chequeIDFieldField, value) <> true) Then
                    Me.chequeIDFieldField = value
                    Me.RaisePropertyChanged("chequeIDField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property depositDateField() As String
            Get
                Return Me.depositDateFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.depositDateFieldField, value) <> true) Then
                    Me.depositDateFieldField = value
                    Me.RaisePropertyChanged("depositDateField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property settlementDateField() As String
            Get
                Return Me.settlementDateFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.settlementDateFieldField, value) <> true) Then
                    Me.settlementDateFieldField = value
                    Me.RaisePropertyChanged("settlementDateField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property userNameField() As String
            Get
                Return Me.userNameFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.userNameFieldField, value) <> true) Then
                    Me.userNameFieldField = value
                    Me.RaisePropertyChanged("userNameField")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Response", [Namespace]:="http://schemas.datacontract.org/2004/07/com.cbi.chakavak.chequeSchema"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Response
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private amendatoryFieldField As Boolean
        
        Private creditorFieldField As ChakavakServiceWS.Creditor
        
        Private debtorFieldField As ChakavakServiceWS.Debtor
        
        Private nonPaymentCertificateFieldField As ChakavakServiceWS.NonPaymentCertificate
        
        Private reasonFieldField As String
        
        Private seqNoFieldField As String
        
        Private statusFieldField As String
        
        Private submitterFieldField As String
        
        Private tRNFieldField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property amendatoryField() As Boolean
            Get
                Return Me.amendatoryFieldField
            End Get
            Set
                If (Me.amendatoryFieldField.Equals(value) <> true) Then
                    Me.amendatoryFieldField = value
                    Me.RaisePropertyChanged("amendatoryField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property creditorField() As ChakavakServiceWS.Creditor
            Get
                Return Me.creditorFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.creditorFieldField, value) <> true) Then
                    Me.creditorFieldField = value
                    Me.RaisePropertyChanged("creditorField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property debtorField() As ChakavakServiceWS.Debtor
            Get
                Return Me.debtorFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.debtorFieldField, value) <> true) Then
                    Me.debtorFieldField = value
                    Me.RaisePropertyChanged("debtorField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property nonPaymentCertificateField() As ChakavakServiceWS.NonPaymentCertificate
            Get
                Return Me.nonPaymentCertificateFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nonPaymentCertificateFieldField, value) <> true) Then
                    Me.nonPaymentCertificateFieldField = value
                    Me.RaisePropertyChanged("nonPaymentCertificateField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property reasonField() As String
            Get
                Return Me.reasonFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.reasonFieldField, value) <> true) Then
                    Me.reasonFieldField = value
                    Me.RaisePropertyChanged("reasonField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property seqNoField() As String
            Get
                Return Me.seqNoFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.seqNoFieldField, value) <> true) Then
                    Me.seqNoFieldField = value
                    Me.RaisePropertyChanged("seqNoField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property statusField() As String
            Get
                Return Me.statusFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.statusFieldField, value) <> true) Then
                    Me.statusFieldField = value
                    Me.RaisePropertyChanged("statusField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property submitterField() As String
            Get
                Return Me.submitterFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.submitterFieldField, value) <> true) Then
                    Me.submitterFieldField = value
                    Me.RaisePropertyChanged("submitterField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property tRNField() As String
            Get
                Return Me.tRNFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.tRNFieldField, value) <> true) Then
                    Me.tRNFieldField = value
                    Me.RaisePropertyChanged("tRNField")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Creditor", [Namespace]:="http://schemas.datacontract.org/2004/07/com.cbi.chakavak.chequeSchema"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Creditor
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private bICFieldField As String
        
        Private branchCodeFieldField As String
        
        Private iBANFieldField As String
        
        Private nameFieldField As String
        
        Private nationalCodeFieldField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property bICField() As String
            Get
                Return Me.bICFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.bICFieldField, value) <> true) Then
                    Me.bICFieldField = value
                    Me.RaisePropertyChanged("bICField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property branchCodeField() As String
            Get
                Return Me.branchCodeFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.branchCodeFieldField, value) <> true) Then
                    Me.branchCodeFieldField = value
                    Me.RaisePropertyChanged("branchCodeField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property iBANField() As String
            Get
                Return Me.iBANFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.iBANFieldField, value) <> true) Then
                    Me.iBANFieldField = value
                    Me.RaisePropertyChanged("iBANField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property nameField() As String
            Get
                Return Me.nameFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameFieldField, value) <> true) Then
                    Me.nameFieldField = value
                    Me.RaisePropertyChanged("nameField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property nationalCodeField() As String
            Get
                Return Me.nationalCodeFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nationalCodeFieldField, value) <> true) Then
                    Me.nationalCodeFieldField = value
                    Me.RaisePropertyChanged("nationalCodeField")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Debtor", [Namespace]:="http://schemas.datacontract.org/2004/07/com.cbi.chakavak.chequeSchema"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Debtor
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private bICFieldField As String
        
        Private branchCodeFieldField As String
        
        Private iBANFieldField As String
        
        Private nameFieldField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property bICField() As String
            Get
                Return Me.bICFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.bICFieldField, value) <> true) Then
                    Me.bICFieldField = value
                    Me.RaisePropertyChanged("bICField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property branchCodeField() As String
            Get
                Return Me.branchCodeFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.branchCodeFieldField, value) <> true) Then
                    Me.branchCodeFieldField = value
                    Me.RaisePropertyChanged("branchCodeField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property iBANField() As String
            Get
                Return Me.iBANFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.iBANFieldField, value) <> true) Then
                    Me.iBANFieldField = value
                    Me.RaisePropertyChanged("iBANField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property nameField() As String
            Get
                Return Me.nameFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameFieldField, value) <> true) Then
                    Me.nameFieldField = value
                    Me.RaisePropertyChanged("nameField")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="NonPaymentCertificate", [Namespace]:="http://schemas.datacontract.org/2004/07/com.cbi.chakavak.chequeSchema"),  _
     System.SerializableAttribute()>  _
    Partial Public Class NonPaymentCertificate
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private authorisedFieldField() As ChakavakServiceWS.Authorised
        
        Private chequeIssuerFieldField As ChakavakServiceWS.ChequeIssuer
        
        Private otherAuthorisedFieldField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property authorisedField() As ChakavakServiceWS.Authorised()
            Get
                Return Me.authorisedFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.authorisedFieldField, value) <> true) Then
                    Me.authorisedFieldField = value
                    Me.RaisePropertyChanged("authorisedField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property chequeIssuerField() As ChakavakServiceWS.ChequeIssuer
            Get
                Return Me.chequeIssuerFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.chequeIssuerFieldField, value) <> true) Then
                    Me.chequeIssuerFieldField = value
                    Me.RaisePropertyChanged("chequeIssuerField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property otherAuthorisedField() As Boolean
            Get
                Return Me.otherAuthorisedFieldField
            End Get
            Set
                If (Me.otherAuthorisedFieldField.Equals(value) <> true) Then
                    Me.otherAuthorisedFieldField = value
                    Me.RaisePropertyChanged("otherAuthorisedField")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ChequeIssuer", [Namespace]:="http://schemas.datacontract.org/2004/07/com.cbi.chakavak.chequeSchema"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ChequeIssuer
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private accountTypeFieldField As String
        
        Private address1FieldField As String
        
        Private address2FieldField As String
        
        Private birthCertNumOrRegNumFieldField As String
        
        Private birthDateOrRegDateFieldField As String
        
        Private curAccBalFieldField As Decimal
        
        Private curAccBalFieldSpecifiedField As Boolean
        
        Private fatherNameFieldField As String
        
        Private isSettledFieldField As Boolean
        
        Private issueLocationOrRegLocationFieldField As String
        
        Private locationCodeFieldField As String
        
        Private nameFieldField As String
        
        Private nationalIDFieldField As String
        
        Private officeCodeFieldField As String
        
        Private onIssueDateAccBalFieldField As System.Nullable(Of Decimal)
        
        Private postalCode1FieldField As String
        
        Private postalCode2FieldField As String
        
        Private referToFieldField As String
        
        Private tel1FieldField As String
        
        Private tel2FieldField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property accountTypeField() As String
            Get
                Return Me.accountTypeFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.accountTypeFieldField, value) <> true) Then
                    Me.accountTypeFieldField = value
                    Me.RaisePropertyChanged("accountTypeField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property address1Field() As String
            Get
                Return Me.address1FieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.address1FieldField, value) <> true) Then
                    Me.address1FieldField = value
                    Me.RaisePropertyChanged("address1Field")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property address2Field() As String
            Get
                Return Me.address2FieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.address2FieldField, value) <> true) Then
                    Me.address2FieldField = value
                    Me.RaisePropertyChanged("address2Field")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property birthCertNumOrRegNumField() As String
            Get
                Return Me.birthCertNumOrRegNumFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.birthCertNumOrRegNumFieldField, value) <> true) Then
                    Me.birthCertNumOrRegNumFieldField = value
                    Me.RaisePropertyChanged("birthCertNumOrRegNumField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property birthDateOrRegDateField() As String
            Get
                Return Me.birthDateOrRegDateFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.birthDateOrRegDateFieldField, value) <> true) Then
                    Me.birthDateOrRegDateFieldField = value
                    Me.RaisePropertyChanged("birthDateOrRegDateField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property curAccBalField() As Decimal
            Get
                Return Me.curAccBalFieldField
            End Get
            Set
                If (Me.curAccBalFieldField.Equals(value) <> true) Then
                    Me.curAccBalFieldField = value
                    Me.RaisePropertyChanged("curAccBalField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property curAccBalFieldSpecified() As Boolean
            Get
                Return Me.curAccBalFieldSpecifiedField
            End Get
            Set
                If (Me.curAccBalFieldSpecifiedField.Equals(value) <> true) Then
                    Me.curAccBalFieldSpecifiedField = value
                    Me.RaisePropertyChanged("curAccBalFieldSpecified")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property fatherNameField() As String
            Get
                Return Me.fatherNameFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fatherNameFieldField, value) <> true) Then
                    Me.fatherNameFieldField = value
                    Me.RaisePropertyChanged("fatherNameField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property isSettledField() As Boolean
            Get
                Return Me.isSettledFieldField
            End Get
            Set
                If (Me.isSettledFieldField.Equals(value) <> true) Then
                    Me.isSettledFieldField = value
                    Me.RaisePropertyChanged("isSettledField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property issueLocationOrRegLocationField() As String
            Get
                Return Me.issueLocationOrRegLocationFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.issueLocationOrRegLocationFieldField, value) <> true) Then
                    Me.issueLocationOrRegLocationFieldField = value
                    Me.RaisePropertyChanged("issueLocationOrRegLocationField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property locationCodeField() As String
            Get
                Return Me.locationCodeFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.locationCodeFieldField, value) <> true) Then
                    Me.locationCodeFieldField = value
                    Me.RaisePropertyChanged("locationCodeField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property nameField() As String
            Get
                Return Me.nameFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameFieldField, value) <> true) Then
                    Me.nameFieldField = value
                    Me.RaisePropertyChanged("nameField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property nationalIDField() As String
            Get
                Return Me.nationalIDFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nationalIDFieldField, value) <> true) Then
                    Me.nationalIDFieldField = value
                    Me.RaisePropertyChanged("nationalIDField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property officeCodeField() As String
            Get
                Return Me.officeCodeFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.officeCodeFieldField, value) <> true) Then
                    Me.officeCodeFieldField = value
                    Me.RaisePropertyChanged("officeCodeField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property onIssueDateAccBalField() As System.Nullable(Of Decimal)
            Get
                Return Me.onIssueDateAccBalFieldField
            End Get
            Set
                If (Me.onIssueDateAccBalFieldField.Equals(value) <> true) Then
                    Me.onIssueDateAccBalFieldField = value
                    Me.RaisePropertyChanged("onIssueDateAccBalField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property postalCode1Field() As String
            Get
                Return Me.postalCode1FieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.postalCode1FieldField, value) <> true) Then
                    Me.postalCode1FieldField = value
                    Me.RaisePropertyChanged("postalCode1Field")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property postalCode2Field() As String
            Get
                Return Me.postalCode2FieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.postalCode2FieldField, value) <> true) Then
                    Me.postalCode2FieldField = value
                    Me.RaisePropertyChanged("postalCode2Field")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property referToField() As String
            Get
                Return Me.referToFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.referToFieldField, value) <> true) Then
                    Me.referToFieldField = value
                    Me.RaisePropertyChanged("referToField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property tel1Field() As String
            Get
                Return Me.tel1FieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.tel1FieldField, value) <> true) Then
                    Me.tel1FieldField = value
                    Me.RaisePropertyChanged("tel1Field")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property tel2Field() As String
            Get
                Return Me.tel2FieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.tel2FieldField, value) <> true) Then
                    Me.tel2FieldField = value
                    Me.RaisePropertyChanged("tel2Field")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Authorised", [Namespace]:="http://schemas.datacontract.org/2004/07/com.cbi.chakavak.chequeSchema"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Authorised
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private address1FieldField As String
        
        Private birthCertNumOrRegNumFieldField As String
        
        Private birthDateOrRegDateFieldField As String
        
        Private fatherNameFieldField As String
        
        Private fullNameFieldField As String
        
        Private issueLocationOrRegLocationFieldField As String
        
        Private locationCodeFieldField As String
        
        Private nationalIDFieldField As String
        
        Private officeCodeFieldField As String
        
        Private postalCode1FieldField As String
        
        Private referToFieldField As String
        
        Private tel1FieldField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property address1Field() As String
            Get
                Return Me.address1FieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.address1FieldField, value) <> true) Then
                    Me.address1FieldField = value
                    Me.RaisePropertyChanged("address1Field")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property birthCertNumOrRegNumField() As String
            Get
                Return Me.birthCertNumOrRegNumFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.birthCertNumOrRegNumFieldField, value) <> true) Then
                    Me.birthCertNumOrRegNumFieldField = value
                    Me.RaisePropertyChanged("birthCertNumOrRegNumField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property birthDateOrRegDateField() As String
            Get
                Return Me.birthDateOrRegDateFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.birthDateOrRegDateFieldField, value) <> true) Then
                    Me.birthDateOrRegDateFieldField = value
                    Me.RaisePropertyChanged("birthDateOrRegDateField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property fatherNameField() As String
            Get
                Return Me.fatherNameFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fatherNameFieldField, value) <> true) Then
                    Me.fatherNameFieldField = value
                    Me.RaisePropertyChanged("fatherNameField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property fullNameField() As String
            Get
                Return Me.fullNameFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fullNameFieldField, value) <> true) Then
                    Me.fullNameFieldField = value
                    Me.RaisePropertyChanged("fullNameField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property issueLocationOrRegLocationField() As String
            Get
                Return Me.issueLocationOrRegLocationFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.issueLocationOrRegLocationFieldField, value) <> true) Then
                    Me.issueLocationOrRegLocationFieldField = value
                    Me.RaisePropertyChanged("issueLocationOrRegLocationField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property locationCodeField() As String
            Get
                Return Me.locationCodeFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.locationCodeFieldField, value) <> true) Then
                    Me.locationCodeFieldField = value
                    Me.RaisePropertyChanged("locationCodeField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property nationalIDField() As String
            Get
                Return Me.nationalIDFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nationalIDFieldField, value) <> true) Then
                    Me.nationalIDFieldField = value
                    Me.RaisePropertyChanged("nationalIDField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property officeCodeField() As String
            Get
                Return Me.officeCodeFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.officeCodeFieldField, value) <> true) Then
                    Me.officeCodeFieldField = value
                    Me.RaisePropertyChanged("officeCodeField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property postalCode1Field() As String
            Get
                Return Me.postalCode1FieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.postalCode1FieldField, value) <> true) Then
                    Me.postalCode1FieldField = value
                    Me.RaisePropertyChanged("postalCode1Field")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property referToField() As String
            Get
                Return Me.referToFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.referToFieldField, value) <> true) Then
                    Me.referToFieldField = value
                    Me.RaisePropertyChanged("referToField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property tel1Field() As String
            Get
                Return Me.tel1FieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.tel1FieldField, value) <> true) Then
                    Me.tel1FieldField = value
                    Me.RaisePropertyChanged("tel1Field")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Result", [Namespace]:="http://schemas.datacontract.org/2004/07/CommonObject"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Result
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResultObjField As Object
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As ChakavakServiceWS.ResultType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Code() As Integer
            Get
                Return Me.CodeField
            End Get
            Set
                If (Me.CodeField.Equals(value) <> true) Then
                    Me.CodeField = value
                    Me.RaisePropertyChanged("Code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ResultObj() As Object
            Get
                Return Me.ResultObjField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResultObjField, value) <> true) Then
                    Me.ResultObjField = value
                    Me.RaisePropertyChanged("ResultObj")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As ChakavakServiceWS.ResultType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResultType", [Namespace]:="http://schemas.datacontract.org/2004/07/CommonObject")>  _
    Public Enum ResultType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Failed = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Success = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ChequeRequest", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ChequeRequest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HeaderField As ChakavakServiceWS.Header
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequestField As ChakavakServiceWS.Request
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Header() As ChakavakServiceWS.Header
            Get
                Return Me.HeaderField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HeaderField, value) <> true) Then
                    Me.HeaderField = value
                    Me.RaisePropertyChanged("Header")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Request() As ChakavakServiceWS.Request
            Get
                Return Me.RequestField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RequestField, value) <> true) Then
                    Me.RequestField = value
                    Me.RaisePropertyChanged("Request")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Request", [Namespace]:="http://schemas.datacontract.org/2004/07/com.cbi.chakavak.chequeSchema"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Request
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private codedFieldField As Boolean
        
        Private creditorFieldField As ChakavakServiceWS.Creditor
        
        Private debtorFieldField As ChakavakServiceWS.Debtor
        
        Private instrIdFieldField As String
        
        Private partialSettlementFieldField As Boolean
        
        Private partialSettlementFieldSpecifiedField As Boolean
        
        Private priorityFieldField As String
        
        Private prominentStampFieldField As Boolean
        
        Private regressiveFieldField As String
        
        Private requestDataFieldField As ChakavakServiceWS.RequestData
        
        Private seqNoFieldField As String
        
        Private submitterFieldField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property codedField() As Boolean
            Get
                Return Me.codedFieldField
            End Get
            Set
                If (Me.codedFieldField.Equals(value) <> true) Then
                    Me.codedFieldField = value
                    Me.RaisePropertyChanged("codedField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property creditorField() As ChakavakServiceWS.Creditor
            Get
                Return Me.creditorFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.creditorFieldField, value) <> true) Then
                    Me.creditorFieldField = value
                    Me.RaisePropertyChanged("creditorField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property debtorField() As ChakavakServiceWS.Debtor
            Get
                Return Me.debtorFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.debtorFieldField, value) <> true) Then
                    Me.debtorFieldField = value
                    Me.RaisePropertyChanged("debtorField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property instrIdField() As String
            Get
                Return Me.instrIdFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.instrIdFieldField, value) <> true) Then
                    Me.instrIdFieldField = value
                    Me.RaisePropertyChanged("instrIdField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property partialSettlementField() As Boolean
            Get
                Return Me.partialSettlementFieldField
            End Get
            Set
                If (Me.partialSettlementFieldField.Equals(value) <> true) Then
                    Me.partialSettlementFieldField = value
                    Me.RaisePropertyChanged("partialSettlementField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property partialSettlementFieldSpecified() As Boolean
            Get
                Return Me.partialSettlementFieldSpecifiedField
            End Get
            Set
                If (Me.partialSettlementFieldSpecifiedField.Equals(value) <> true) Then
                    Me.partialSettlementFieldSpecifiedField = value
                    Me.RaisePropertyChanged("partialSettlementFieldSpecified")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property priorityField() As String
            Get
                Return Me.priorityFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.priorityFieldField, value) <> true) Then
                    Me.priorityFieldField = value
                    Me.RaisePropertyChanged("priorityField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property prominentStampField() As Boolean
            Get
                Return Me.prominentStampFieldField
            End Get
            Set
                If (Me.prominentStampFieldField.Equals(value) <> true) Then
                    Me.prominentStampFieldField = value
                    Me.RaisePropertyChanged("prominentStampField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property regressiveField() As String
            Get
                Return Me.regressiveFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.regressiveFieldField, value) <> true) Then
                    Me.regressiveFieldField = value
                    Me.RaisePropertyChanged("regressiveField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property requestDataField() As ChakavakServiceWS.RequestData
            Get
                Return Me.requestDataFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.requestDataFieldField, value) <> true) Then
                    Me.requestDataFieldField = value
                    Me.RaisePropertyChanged("requestDataField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property seqNoField() As String
            Get
                Return Me.seqNoFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.seqNoFieldField, value) <> true) Then
                    Me.seqNoFieldField = value
                    Me.RaisePropertyChanged("seqNoField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property submitterField() As String
            Get
                Return Me.submitterFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.submitterFieldField, value) <> true) Then
                    Me.submitterFieldField = value
                    Me.RaisePropertyChanged("submitterField")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RequestData", [Namespace]:="http://schemas.datacontract.org/2004/07/com.cbi.chakavak.chequeSchema"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RequestData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private backFieldField() As Byte
        
        Private frontFieldField() As Byte
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property backField() As Byte()
            Get
                Return Me.backFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.backFieldField, value) <> true) Then
                    Me.backFieldField = value
                    Me.RaisePropertyChanged("backField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property frontField() As Byte()
            Get
                Return Me.frontFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.frontFieldField, value) <> true) Then
                    Me.frontFieldField = value
                    Me.RaisePropertyChanged("frontField")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ChakavakServiceWS.IChakavakService")>  _
    Public Interface IChakavakService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChakavakService/PutResponseOutChequeResponse", ReplyAction:="http://tempuri.org/IChakavakService/PutResponseOutChequeResponseResponse")>  _
        Function PutResponseOutChequeResponse(ByVal param As ChakavakServiceWS.ChequeResponse) As ChakavakServiceWS.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChakavakService/PutRequestOutChequeRequest", ReplyAction:="http://tempuri.org/IChakavakService/PutRequestOutChequeRequestResponse")>  _
        Function PutRequestOutChequeRequest(ByVal param As ChakavakServiceWS.ChequeRequest) As ChakavakServiceWS.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChakavakService/GetRequestInChequeRequest", ReplyAction:="http://tempuri.org/IChakavakService/GetRequestInChequeRequestResponse")>  _
        Function GetRequestInChequeRequest() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChakavakService/GetResponseInChequeResponse", ReplyAction:="http://tempuri.org/IChakavakService/GetResponseInChequeResponseResponse")>  _
        Function GetResponseInChequeResponse() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChakavakService/GetRequestInAcknowledge", ReplyAction:="http://tempuri.org/IChakavakService/GetRequestInAcknowledgeResponse")>  _
        Function GetRequestInAcknowledge(ByVal chequeId As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChakavakService/GetRequestInAcknowledgeNotProcessed", ReplyAction:="http://tempuri.org/IChakavakService/GetRequestInAcknowledgeNotProcessedResponse")>  _
        Function GetRequestInAcknowledgeNotProcessed() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChakavakService/GetResponseInAcknowledgeNotProcessed", ReplyAction:="http://tempuri.org/IChakavakService/GetResponseInAcknowledgeNotProcessedResponse")>  _
        Function GetResponseInAcknowledgeNotProcessed() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChakavakService/GetInformationSchemaNotProcessed", ReplyAction:="http://tempuri.org/IChakavakService/GetInformationSchemaNotProcessedResponse")>  _
        Function GetInformationSchemaNotProcessed() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChakavakService/UpdateRequestInItems", ReplyAction:="http://tempuri.org/IChakavakService/UpdateRequestInItemsResponse")>  _
        Function UpdateRequestInItems(ByVal ids() As Long) As ChakavakServiceWS.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChakavakService/UpdateRequestInItemsBySeqNo", ReplyAction:="http://tempuri.org/IChakavakService/UpdateRequestInItemsBySeqNoResponse")>  _
        Function UpdateRequestInItemsBySeqNo(ByVal seqNos() As String) As ChakavakServiceWS.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChakavakService/UpdateResponseInItemsBySeqNo", ReplyAction:="http://tempuri.org/IChakavakService/UpdateResponseInItemsBySeqNoResponse")>  _
        Function UpdateResponseInItemsBySeqNo(ByVal seqNos() As String) As ChakavakServiceWS.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChakavakService/UpdateRequestInAcknowledgeItemsByTRN", ReplyAction:="http://tempuri.org/IChakavakService/UpdateRequestInAcknowledgeItemsByTRNResponse")>  _
        Function UpdateRequestInAcknowledgeItemsByTRN(ByVal trns() As String) As ChakavakServiceWS.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChakavakService/UpdateResponseInAcknowledgeItemsByTRN", ReplyAction:="http://tempuri.org/IChakavakService/UpdateResponseInAcknowledgeItemsByTRNResponse"& _ 
            "")>  _
        Function UpdateResponseInAcknowledgeItemsByTRN(ByVal trns() As String) As ChakavakServiceWS.Result
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IChakavakServiceChannel
        Inherits ChakavakServiceWS.IChakavakService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ChakavakServiceClient
        Inherits System.ServiceModel.ClientBase(Of ChakavakServiceWS.IChakavakService)
        Implements ChakavakServiceWS.IChakavakService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function PutResponseOutChequeResponse(ByVal param As ChakavakServiceWS.ChequeResponse) As ChakavakServiceWS.Result Implements ChakavakServiceWS.IChakavakService.PutResponseOutChequeResponse
            Return MyBase.Channel.PutResponseOutChequeResponse(param)
        End Function
        
        Public Function PutRequestOutChequeRequest(ByVal param As ChakavakServiceWS.ChequeRequest) As ChakavakServiceWS.Result Implements ChakavakServiceWS.IChakavakService.PutRequestOutChequeRequest
            Return MyBase.Channel.PutRequestOutChequeRequest(param)
        End Function
        
        Public Function GetRequestInChequeRequest() As String Implements ChakavakServiceWS.IChakavakService.GetRequestInChequeRequest
            Return MyBase.Channel.GetRequestInChequeRequest
        End Function
        
        Public Function GetResponseInChequeResponse() As String Implements ChakavakServiceWS.IChakavakService.GetResponseInChequeResponse
            Return MyBase.Channel.GetResponseInChequeResponse
        End Function
        
        Public Function GetRequestInAcknowledge(ByVal chequeId As String) As String Implements ChakavakServiceWS.IChakavakService.GetRequestInAcknowledge
            Return MyBase.Channel.GetRequestInAcknowledge(chequeId)
        End Function
        
        Public Function GetRequestInAcknowledgeNotProcessed() As String Implements ChakavakServiceWS.IChakavakService.GetRequestInAcknowledgeNotProcessed
            Return MyBase.Channel.GetRequestInAcknowledgeNotProcessed
        End Function
        
        Public Function GetResponseInAcknowledgeNotProcessed() As String Implements ChakavakServiceWS.IChakavakService.GetResponseInAcknowledgeNotProcessed
            Return MyBase.Channel.GetResponseInAcknowledgeNotProcessed
        End Function
        
        Public Function GetInformationSchemaNotProcessed() As String Implements ChakavakServiceWS.IChakavakService.GetInformationSchemaNotProcessed
            Return MyBase.Channel.GetInformationSchemaNotProcessed
        End Function
        
        Public Function UpdateRequestInItems(ByVal ids() As Long) As ChakavakServiceWS.Result Implements ChakavakServiceWS.IChakavakService.UpdateRequestInItems
            Return MyBase.Channel.UpdateRequestInItems(ids)
        End Function
        
        Public Function UpdateRequestInItemsBySeqNo(ByVal seqNos() As String) As ChakavakServiceWS.Result Implements ChakavakServiceWS.IChakavakService.UpdateRequestInItemsBySeqNo
            Return MyBase.Channel.UpdateRequestInItemsBySeqNo(seqNos)
        End Function
        
        Public Function UpdateResponseInItemsBySeqNo(ByVal seqNos() As String) As ChakavakServiceWS.Result Implements ChakavakServiceWS.IChakavakService.UpdateResponseInItemsBySeqNo
            Return MyBase.Channel.UpdateResponseInItemsBySeqNo(seqNos)
        End Function
        
        Public Function UpdateRequestInAcknowledgeItemsByTRN(ByVal trns() As String) As ChakavakServiceWS.Result Implements ChakavakServiceWS.IChakavakService.UpdateRequestInAcknowledgeItemsByTRN
            Return MyBase.Channel.UpdateRequestInAcknowledgeItemsByTRN(trns)
        End Function
        
        Public Function UpdateResponseInAcknowledgeItemsByTRN(ByVal trns() As String) As ChakavakServiceWS.Result Implements ChakavakServiceWS.IChakavakService.UpdateResponseInAcknowledgeItemsByTRN
            Return MyBase.Channel.UpdateResponseInAcknowledgeItemsByTRN(trns)
        End Function
    End Class
End Namespace
