'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FarazService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://tempuri.org/PBIService/PublicService", ConfigurationName:="FarazService.PublicServiceSoap")>  _
    Public Interface PublicServiceSoap
        
        'CODEGEN: Generating message contract since element name iban from namespace http://tempuri.org/PBIService/PublicService is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PBIService/PublicService/GetAccountByIBAN", ReplyAction:="*")>  _
        Function GetAccountByIBAN(ByVal request As FarazService.GetAccountByIBANRequest) As FarazService.GetAccountByIBANResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAccountByIBANRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAccountByIBAN", [Namespace]:="http://tempuri.org/PBIService/PublicService", Order:=0)>  _
        Public Body As FarazService.GetAccountByIBANRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FarazService.GetAccountByIBANRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/PBIService/PublicService")>  _
    Partial Public Class GetAccountByIBANRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public iban As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal iban As String)
            MyBase.New
            Me.iban = iban
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAccountByIBANResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAccountByIBANResponse", [Namespace]:="http://tempuri.org/PBIService/PublicService", Order:=0)>  _
        Public Body As FarazService.GetAccountByIBANResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As FarazService.GetAccountByIBANResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/PBIService/PublicService")>  _
    Partial Public Class GetAccountByIBANResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetAccountByIBANResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetAccountByIBANResult As String)
            MyBase.New
            Me.GetAccountByIBANResult = GetAccountByIBANResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface PublicServiceSoapChannel
        Inherits FarazService.PublicServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PublicServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of FarazService.PublicServiceSoap)
        Implements FarazService.PublicServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function FarazService_PublicServiceSoap_GetAccountByIBAN(ByVal request As FarazService.GetAccountByIBANRequest) As FarazService.GetAccountByIBANResponse Implements FarazService.PublicServiceSoap.GetAccountByIBAN
            Return MyBase.Channel.GetAccountByIBAN(request)
        End Function
        
        Public Function GetAccountByIBAN(ByVal iban As String) As String
            Dim inValue As FarazService.GetAccountByIBANRequest = New FarazService.GetAccountByIBANRequest()
            inValue.Body = New FarazService.GetAccountByIBANRequestBody()
            inValue.Body.iban = iban
            Dim retVal As FarazService.GetAccountByIBANResponse = CType(Me,FarazService.PublicServiceSoap).GetAccountByIBAN(inValue)
            Return retVal.Body.GetAccountByIBANResult
        End Function
    End Class
End Namespace
